# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


variables:
  AzureSubscription: '<Visual Studio Enterprise Subscription – MPN(9aa09752-a676-4df1-8cf9-02cefca9f960)>'
  ResourceGroupName: '<New_Rg1>'
  ServerName: '<testserver-12.database.windows.net>'
  ServerFqdn: '<DATABASE_FQDN>'
  DatabaseName: '<sample-db>'
  AdminUser: '<Admin24>'
  AdminPassword: '<My_localuser>'
  SQLFile: '<C:\Users\GOPINA~1\AppData\Local\Temp\~vs1DAD.sql$(Build.SourcesDirectory)>'

steps:
- task: AzurePowerShell@5
  displayName: 'Azure PowerShell script'
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription – MPN(9aa09752-a676-4df1-8cf9-02cefca9f960)'
    ScriptType: 'filePath'
    ScriptPath: '$(Build.SourcesDirectory)\scripts\SetAzureFirewallRule.ps1'
    ScriptArguments: '-ServerName $(testserver-12.database.windows.net) -ResourceGroupName $(New_Rg1)'
    azurePowerShellVersion: 'LatestVersion'

- task: CmdLine@2
  displayName: Run Sqlcmd
  inputs:
    filename: sqlcmd
    arguments: '-S $(ServerFqdn) -U $(AdminUser) -P $(AdminPassword) -d $(DatabaseName) -i $(SQLFile)'

- task: AzurePowerShell@5
  displayName: 'Azure PowerShell script'
  inputs:
    azureSubscription: '$(Visual Studio Enterprise Subscription – MPN(9aa09752-a676-4df1-8cf9-02cefca9f960))'
    ScriptType: filePath
    ScriptPath: '$(Build.SourcesDirectory)\scripts\RemoveAzureFirewallRule.ps1'
    ScriptArguments: '-ServerName $(testserver-12.database.windows.net) -ResourceGroupName $(New_Rg1)'
    azurePowerShellVersion: LatestVersion