# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  - group: 'AzureSQLConnection'
  - name: 'dacpacFilePath'
    value: '$(System.DefaultWorkingDirectory)/sample-db/bin/Release/sample-db.dacpac'

jobs:
- job: DeployDatabaseChanges
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)'
    artifactName: 'drop'
  

  - powershell: |
      Expand-Archive -Path '$(System.DefaultWorkingDirectory)/sqlpackage-linux-x64-latest.tar.gz' -DestinationPath '$(System.DefaultWorkingDirectory)/sqlpackage'
    displayName: 'Extract sqlpackage'

  - script: |
      $(System.DefaultWorkingDirectory)/sqlpackage/sqlpackage /a:Publish /sf:$(dacpacFilePath) /tsn:$(testserver-12.database.windows.net).database.windows.net /tdn:$(sample-db) /tu:$(Admin24) /tp:$(My_localuser) /p:CommandTimeout=1200
    displayName: 'Deploy database changes'

  - powershell: |
      # Additional tasks or cleanup if needed
    displayName: 'Additional tasks'
